// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: purchase/purchase.proto

package purchase

import (
	context "context"
	rpc "github.com/ndtdat/social-network-monorepo/purchase-service/pkg/api/go/purchase/rpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Purchase_IAllocateVoucherByCampaignID_FullMethodName = "/purchase.Purchase/IAllocateVoucherByCampaignID"
)

// PurchaseClient is the client API for Purchase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PurchaseClient interface {
	IAllocateVoucherByCampaignID(ctx context.Context, in *rpc.IAllocateVoucherByCampaignIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type purchaseClient struct {
	cc grpc.ClientConnInterface
}

func NewPurchaseClient(cc grpc.ClientConnInterface) PurchaseClient {
	return &purchaseClient{cc}
}

func (c *purchaseClient) IAllocateVoucherByCampaignID(ctx context.Context, in *rpc.IAllocateVoucherByCampaignIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Purchase_IAllocateVoucherByCampaignID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseServer is the server API for Purchase service.
// All implementations must embed UnimplementedPurchaseServer
// for forward compatibility
type PurchaseServer interface {
	IAllocateVoucherByCampaignID(context.Context, *rpc.IAllocateVoucherByCampaignIDRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPurchaseServer()
}

// UnimplementedPurchaseServer must be embedded to have forward compatible implementations.
type UnimplementedPurchaseServer struct {
}

func (UnimplementedPurchaseServer) IAllocateVoucherByCampaignID(context.Context, *rpc.IAllocateVoucherByCampaignIDRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IAllocateVoucherByCampaignID not implemented")
}
func (UnimplementedPurchaseServer) mustEmbedUnimplementedPurchaseServer() {}

// UnsafePurchaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PurchaseServer will
// result in compilation errors.
type UnsafePurchaseServer interface {
	mustEmbedUnimplementedPurchaseServer()
}

func RegisterPurchaseServer(s grpc.ServiceRegistrar, srv PurchaseServer) {
	s.RegisterService(&Purchase_ServiceDesc, srv)
}

func _Purchase_IAllocateVoucherByCampaignID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rpc.IAllocateVoucherByCampaignIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServer).IAllocateVoucherByCampaignID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Purchase_IAllocateVoucherByCampaignID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServer).IAllocateVoucherByCampaignID(ctx, req.(*rpc.IAllocateVoucherByCampaignIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Purchase_ServiceDesc is the grpc.ServiceDesc for Purchase service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Purchase_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "purchase.Purchase",
	HandlerType: (*PurchaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IAllocateVoucherByCampaignID",
			Handler:    _Purchase_IAllocateVoucherByCampaignID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "purchase/purchase.proto",
}
