// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: purchase/model/detailed_subscription_plan.proto

package model

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DetailedSubscriptionPlan with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DetailedSubscriptionPlan) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DetailedSubscriptionPlan with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DetailedSubscriptionPlanMultiError, or nil if none found.
func (m *DetailedSubscriptionPlan) ValidateAll() error {
	return m.validate(true)
}

func (m *DetailedSubscriptionPlan) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for SubscriptionPlanId

	// no validation rules for Tier

	// no validation rules for CurrencySymbol

	// no validation rules for Amount

	// no validation rules for DiscountAmount

	if len(errors) > 0 {
		return DetailedSubscriptionPlanMultiError(errors)
	}

	return nil
}

// DetailedSubscriptionPlanMultiError is an error wrapping multiple validation
// errors returned by DetailedSubscriptionPlan.ValidateAll() if the designated
// constraints aren't met.
type DetailedSubscriptionPlanMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetailedSubscriptionPlanMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetailedSubscriptionPlanMultiError) AllErrors() []error { return m }

// DetailedSubscriptionPlanValidationError is the validation error returned by
// DetailedSubscriptionPlan.Validate if the designated constraints aren't met.
type DetailedSubscriptionPlanValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetailedSubscriptionPlanValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetailedSubscriptionPlanValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetailedSubscriptionPlanValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetailedSubscriptionPlanValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetailedSubscriptionPlanValidationError) ErrorName() string {
	return "DetailedSubscriptionPlanValidationError"
}

// Error satisfies the builtin error interface
func (e DetailedSubscriptionPlanValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetailedSubscriptionPlan.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetailedSubscriptionPlanValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetailedSubscriptionPlanValidationError{}
