// Code generated by protoc-gen-go-gorm-enum. DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"fmt"
)

func (x *SubscriptionPlanTier) Scan(value any) error {
	*x = SubscriptionPlanTier(SubscriptionPlanTier_value[string(value.([]byte))])

	return nil
}

func (x SubscriptionPlanTier) Value() (driver.Value, error) {
	return x.String(), nil
}

func SubscriptionPlanTier_FromString(str string) (SubscriptionPlanTier, error) {
	value, ok := SubscriptionPlanTier_value[str]
	if !ok {
		return SubscriptionPlanTier(0), fmt.Errorf("cannot parse SubscriptionPlanTier from %s", str)
	}

	return SubscriptionPlanTier(value), nil
}

func SubscriptionPlanTier_MustParseFromString(str string) SubscriptionPlanTier {
	value, ok := SubscriptionPlanTier_value[str]
	if !ok {
		panic(fmt.Errorf("cannot parse SubscriptionPlanTier from %s", str))
	}

	return SubscriptionPlanTier(value)
}
