// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        (unknown)
// source: purchase/model/voucher_status.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoucherStatus int32

const (
	VoucherStatus_VS_NONE        VoucherStatus = 0
	VoucherStatus_VS_DRAFT       VoucherStatus = 1
	VoucherStatus_VS_AVAILABLE   VoucherStatus = 2
	VoucherStatus_VS_UNAVAILABLE VoucherStatus = 3
)

// Enum value maps for VoucherStatus.
var (
	VoucherStatus_name = map[int32]string{
		0: "VS_NONE",
		1: "VS_DRAFT",
		2: "VS_AVAILABLE",
		3: "VS_UNAVAILABLE",
	}
	VoucherStatus_value = map[string]int32{
		"VS_NONE":        0,
		"VS_DRAFT":       1,
		"VS_AVAILABLE":   2,
		"VS_UNAVAILABLE": 3,
	}
)

func (x VoucherStatus) Enum() *VoucherStatus {
	p := new(VoucherStatus)
	*p = x
	return p
}

func (x VoucherStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoucherStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_purchase_model_voucher_status_proto_enumTypes[0].Descriptor()
}

func (VoucherStatus) Type() protoreflect.EnumType {
	return &file_purchase_model_voucher_status_proto_enumTypes[0]
}

func (x VoucherStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoucherStatus.Descriptor instead.
func (VoucherStatus) EnumDescriptor() ([]byte, []int) {
	return file_purchase_model_voucher_status_proto_rawDescGZIP(), []int{0}
}

var File_purchase_model_voucher_status_proto protoreflect.FileDescriptor

var file_purchase_model_voucher_status_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2a, 0x50, 0x0a, 0x0d,
	0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x56, 0x53, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x53,
	0x5f, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x56, 0x53, 0x5f, 0x41,
	0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x56, 0x53,
	0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x42, 0x5e,
	0x48, 0x01, 0x5a, 0x5a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e,
	0x64, 0x74, 0x64, 0x61, 0x74, 0x2f, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2d, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x6d, 0x6f, 0x6e, 0x6f, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_purchase_model_voucher_status_proto_rawDescOnce sync.Once
	file_purchase_model_voucher_status_proto_rawDescData = file_purchase_model_voucher_status_proto_rawDesc
)

func file_purchase_model_voucher_status_proto_rawDescGZIP() []byte {
	file_purchase_model_voucher_status_proto_rawDescOnce.Do(func() {
		file_purchase_model_voucher_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_purchase_model_voucher_status_proto_rawDescData)
	})
	return file_purchase_model_voucher_status_proto_rawDescData
}

var file_purchase_model_voucher_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_purchase_model_voucher_status_proto_goTypes = []interface{}{
	(VoucherStatus)(0), // 0: model.VoucherStatus
}
var file_purchase_model_voucher_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_purchase_model_voucher_status_proto_init() }
func file_purchase_model_voucher_status_proto_init() {
	if File_purchase_model_voucher_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_purchase_model_voucher_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_purchase_model_voucher_status_proto_goTypes,
		DependencyIndexes: file_purchase_model_voucher_status_proto_depIdxs,
		EnumInfos:         file_purchase_model_voucher_status_proto_enumTypes,
	}.Build()
	File_purchase_model_voucher_status_proto = out.File
	file_purchase_model_voucher_status_proto_rawDesc = nil
	file_purchase_model_voucher_status_proto_goTypes = nil
	file_purchase_model_voucher_status_proto_depIdxs = nil
}
