// Code generated by protoc-gen-go-gorm-enum. DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"fmt"
)

func (x *VoucherGroupType) Scan(value any) error {
	*x = VoucherGroupType(VoucherGroupType_value[string(value.([]byte))])

	return nil
}

func (x VoucherGroupType) Value() (driver.Value, error) {
	return x.String(), nil
}

func VoucherGroupType_FromString(str string) (VoucherGroupType, error) {
	value, ok := VoucherGroupType_value[str]
	if !ok {
		return VoucherGroupType(0), fmt.Errorf("cannot parse VoucherGroupType from %s", str)
	}

	return VoucherGroupType(value), nil
}

func VoucherGroupType_MustParseFromString(str string) VoucherGroupType {
	value, ok := VoucherGroupType_value[str]
	if !ok {
		panic(fmt.Errorf("cannot parse VoucherGroupType from %s", str))
	}

	return VoucherGroupType(value)
}
