// Code generated by protoc-gen-go-gorm-enum. DO NOT EDIT.

package model

import (
	"database/sql/driver"
	"fmt"
)

func (x *VoucherCalculationType) Scan(value any) error {
	*x = VoucherCalculationType(VoucherCalculationType_value[string(value.([]byte))])

	return nil
}

func (x VoucherCalculationType) Value() (driver.Value, error) {
	return x.String(), nil
}

func VoucherCalculationType_FromString(str string) (VoucherCalculationType, error) {
	value, ok := VoucherCalculationType_value[str]
	if !ok {
		return VoucherCalculationType(0), fmt.Errorf("cannot parse VoucherCalculationType from %s", str)
	}

	return VoucherCalculationType(value), nil
}

func VoucherCalculationType_MustParseFromString(str string) VoucherCalculationType {
	value, ok := VoucherCalculationType_value[str]
	if !ok {
		panic(fmt.Errorf("cannot parse VoucherCalculationType from %s", str))
	}

	return VoucherCalculationType(value)
}
