// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: purchase/rpc/buy_subscription_plan.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BuySubscriptionPlanRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BuySubscriptionPlanRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BuySubscriptionPlanRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BuySubscriptionPlanRequestMultiError, or nil if none found.
func (m *BuySubscriptionPlanRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BuySubscriptionPlanRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSubscriptionPlanId() <= 1 {
		err := BuySubscriptionPlanRequestValidationError{
			field:  "SubscriptionPlanId",
			reason: "value must be greater than 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BuySubscriptionPlanRequestMultiError(errors)
	}

	return nil
}

// BuySubscriptionPlanRequestMultiError is an error wrapping multiple
// validation errors returned by BuySubscriptionPlanRequest.ValidateAll() if
// the designated constraints aren't met.
type BuySubscriptionPlanRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BuySubscriptionPlanRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BuySubscriptionPlanRequestMultiError) AllErrors() []error { return m }

// BuySubscriptionPlanRequestValidationError is the validation error returned
// by BuySubscriptionPlanRequest.Validate if the designated constraints aren't met.
type BuySubscriptionPlanRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BuySubscriptionPlanRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BuySubscriptionPlanRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BuySubscriptionPlanRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BuySubscriptionPlanRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BuySubscriptionPlanRequestValidationError) ErrorName() string {
	return "BuySubscriptionPlanRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BuySubscriptionPlanRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBuySubscriptionPlanRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BuySubscriptionPlanRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BuySubscriptionPlanRequestValidationError{}

// Validate checks the field values on BuySubscriptionPlanReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BuySubscriptionPlanReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BuySubscriptionPlanReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BuySubscriptionPlanReplyMultiError, or nil if none found.
func (m *BuySubscriptionPlanReply) ValidateAll() error {
	return m.validate(true)
}

func (m *BuySubscriptionPlanReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BuySubscriptionPlanReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BuySubscriptionPlanReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BuySubscriptionPlanReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BuySubscriptionPlanReplyMultiError(errors)
	}

	return nil
}

// BuySubscriptionPlanReplyMultiError is an error wrapping multiple validation
// errors returned by BuySubscriptionPlanReply.ValidateAll() if the designated
// constraints aren't met.
type BuySubscriptionPlanReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BuySubscriptionPlanReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BuySubscriptionPlanReplyMultiError) AllErrors() []error { return m }

// BuySubscriptionPlanReplyValidationError is the validation error returned by
// BuySubscriptionPlanReply.Validate if the designated constraints aren't met.
type BuySubscriptionPlanReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BuySubscriptionPlanReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BuySubscriptionPlanReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BuySubscriptionPlanReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BuySubscriptionPlanReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BuySubscriptionPlanReplyValidationError) ErrorName() string {
	return "BuySubscriptionPlanReplyValidationError"
}

// Error satisfies the builtin error interface
func (e BuySubscriptionPlanReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBuySubscriptionPlanReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BuySubscriptionPlanReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BuySubscriptionPlanReplyValidationError{}
