// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: purchase/rpc/i_allocate_voucher_by_campaign_id.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IAllocateVoucherByCampaignIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *IAllocateVoucherByCampaignIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IAllocateVoucherByCampaignIDRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// IAllocateVoucherByCampaignIDRequestMultiError, or nil if none found.
func (m *IAllocateVoucherByCampaignIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IAllocateVoucherByCampaignIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 1 {
		err := IAllocateVoucherByCampaignIDRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCampaignId() <= 1 {
		err := IAllocateVoucherByCampaignIDRequestValidationError{
			field:  "CampaignId",
			reason: "value must be greater than 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return IAllocateVoucherByCampaignIDRequestMultiError(errors)
	}

	return nil
}

// IAllocateVoucherByCampaignIDRequestMultiError is an error wrapping multiple
// validation errors returned by
// IAllocateVoucherByCampaignIDRequest.ValidateAll() if the designated
// constraints aren't met.
type IAllocateVoucherByCampaignIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IAllocateVoucherByCampaignIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IAllocateVoucherByCampaignIDRequestMultiError) AllErrors() []error { return m }

// IAllocateVoucherByCampaignIDRequestValidationError is the validation error
// returned by IAllocateVoucherByCampaignIDRequest.Validate if the designated
// constraints aren't met.
type IAllocateVoucherByCampaignIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IAllocateVoucherByCampaignIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IAllocateVoucherByCampaignIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IAllocateVoucherByCampaignIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IAllocateVoucherByCampaignIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IAllocateVoucherByCampaignIDRequestValidationError) ErrorName() string {
	return "IAllocateVoucherByCampaignIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e IAllocateVoucherByCampaignIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIAllocateVoucherByCampaignIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IAllocateVoucherByCampaignIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IAllocateVoucherByCampaignIDRequestValidationError{}
