// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        (unknown)
// source: purchase/rpc/i_allocate_voucher_by_campaign_id.proto

package rpc

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IAllocateVoucherByCampaignIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId uint64 `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
}

func (x *IAllocateVoucherByCampaignIDRequest) Reset() {
	*x = IAllocateVoucherByCampaignIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IAllocateVoucherByCampaignIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IAllocateVoucherByCampaignIDRequest) ProtoMessage() {}

func (x *IAllocateVoucherByCampaignIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IAllocateVoucherByCampaignIDRequest.ProtoReflect.Descriptor instead.
func (*IAllocateVoucherByCampaignIDRequest) Descriptor() ([]byte, []int) {
	return file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescGZIP(), []int{0}
}

func (x *IAllocateVoucherByCampaignIDRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IAllocateVoucherByCampaignIDRequest) GetCampaignId() uint64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

var File_purchase_rpc_i_allocate_voucher_by_campaign_id_proto protoreflect.FileDescriptor

var file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDesc = []byte{
	0x0a, 0x34, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x69,
	0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x6f, 0x75, 0x63, 0x68, 0x65,
	0x72, 0x5f, 0x62, 0x79, 0x5f, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x23, 0x49, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x65, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69,
	0x67, 0x6e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x32, 0x02, 0x20, 0x01, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x0b, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x01, 0x52, 0x0a, 0x63, 0x61, 0x6d,
	0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x42, 0x5a, 0x48, 0x01, 0x5a, 0x56, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x64, 0x74, 0x64, 0x61, 0x74, 0x2f, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x6d, 0x6f,
	0x6e, 0x6f, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x6f, 0x2f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x3b,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescOnce sync.Once
	file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescData = file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDesc
)

func file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescGZIP() []byte {
	file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescOnce.Do(func() {
		file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescData)
	})
	return file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDescData
}

var file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_goTypes = []interface{}{
	(*IAllocateVoucherByCampaignIDRequest)(nil), // 0: rpc.IAllocateVoucherByCampaignIDRequest
}
var file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_init() }
func file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_init() {
	if File_purchase_rpc_i_allocate_voucher_by_campaign_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IAllocateVoucherByCampaignIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_goTypes,
		DependencyIndexes: file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_depIdxs,
		MessageInfos:      file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_msgTypes,
	}.Build()
	File_purchase_rpc_i_allocate_voucher_by_campaign_id_proto = out.File
	file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_rawDesc = nil
	file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_goTypes = nil
	file_purchase_rpc_i_allocate_voucher_by_campaign_id_proto_depIdxs = nil
}
