services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    command:
      - --authentication_policy=mysql_native_password
      - --init-file=/schema/init_db.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=5cbcc73a0ba2be5
      - MYSQL_ROOT_HOST=%
    expose:
      - 3306
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
      - ./schema:/schema

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - 6380:6380
    command: redis-server --port 6380 --appendonly yes --replica-read-only no
    logging:
      options:
        max-file: "2"
        max-size: 10m

volumes:
  db:
